### ISSUE TITLE
[uploading]: after uploading finished, have js popup say "Please sign and publish!"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#12]

**Comment by dnelband** [comment]
done, now sign + publish is automatic (user doesnt need to do anything). clone new version to test

**Comment by haschimoto** [comment]
okay, but then dont redirect to Videorama, go to user main site and say little popup "Video added and published!"

**Comment by dnelband** [comment]
done, clone new vide0rama user to test
