### ISSUE TITLE
[user]: files are essentially DOUBLED: This has priority to fix

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#24]
![snap 2016-08-26 at 00 18 03](https://cloud.githubusercontent.com/assets/20817185/17987848/b7cd5a28-6b22-11e6-9efc-b6267bf0a790.png)
That is against any sane logic to implement, there needs to be a way to just use one format for distribution.

**Comment by dnelband** [comment]
the reason for this is that firefox doesnt allow to play media file from an external source within an iframe. but it would be better to drop the .json format and find another solution on firefox. should i drop the .json completely?
