### ISSUE TITLE
[user]: everything under "USER" should be optional

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#26]
![snap 2016-08-26 at 21 51 55](https://cloud.githubusercontent.com/assets/20817185/18018472/6ee524de-6bd7-11e6-8b58-a5a5e5b2305c.png)

**Comment by dnelband** [comment]
1 - everything  is optional, i didnt change that
2 - what makes you think its not? "missing files" has nothing to do with optional or not
