### ISSUE TITLE
[user]: weird files listed under "missing"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#28]
![snap 2016-08-27 at 12 06 44](https://cloud.githubusercontent.com/assets/20817185/18026659/cfd20af6-6c4e-11e6-9ff0-e305f2b14b00.png)

upload.ht/... and
uploa/....

Is that correct?

**Comment by dnelband** [comment]
Couldnt reproduce, do you still see it?
