### ISSUE TITLE
[central]: add comments per video

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#3]

**Comment by dnelband** [comment]
done

**Comment by haschimoto** [comment]
i can select userid, but still comment is posted with hash:
![snap 2016-08-11 at 20 10 12](https://cloud.githubusercontent.com/assets/20817185/17600524/312b14de-6004-11e6-9155-018d09b376e4.png)

**Comment by dnelband** [comment]
seems to work, though takes a while for the sites to update with other comments. please test and report any console errors / notices

**Comment by dnelband** [comment]
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/?c=1PP34sdjvazPUvCGs7cUp8wLUwYRsdDT24v=1

now updates on refresh, no error message. please test local as well.

should i make it auto update every x minutes? like a chat? or is it ok like this?

**Comment by haschimoto** [comment]
dont auto-update, just leave like that.
