### ISSUE TITLE
[central]: clicking on videofilename results in an error

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#43]
![snap 2016-09-11 at 11 19 36](https://cloud.githubusercontent.com/assets/20817185/18416334/b6fd18f8-7811-11e6-9a9e-bb0e4a411d64.png)

**Comment by dnelband** [comment]
now clicking on vid name leads to video view on channel site. is it ok like this? or should i remove the link alltogether?
