### ISSUE TITLE
[central]: comments are not stored

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#44]
maybe yours are stored because you also own the main channel

**Comment by dnelband** [comment]
fixed, test local & bit.no

**Comment by haschimoto** [comment]
comments are not stored, i tried several times

**Comment by haschimoto** [comment]
maybe yours are stored because you also own the main channel

**Comment by haschimoto** [comment]
i keep getting errors of non matching hashes btw for central, maybe its related:
![snap 2016-09-12 at 18 42 19](https://cloud.githubusercontent.com/assets/20817185/18444252/ba2490d0-7918-11e6-9426-d566b150c801.png)

**Comment by haschimoto** [comment]
zerovidz.db probably the most important to not match

**Comment by haschimoto** [comment]
i think the order looks wrong!!
![snap 2016-09-13 at 12 12 45](https://cloud.githubusercontent.com/assets/20817185/18470141/8f7777a6-79ab-11e6-9ec4-3bbea8a645be.png)
