### ISSUE TITLE
[central]: single video page doesnt load fully for some videos

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#46]
e.g. http://127.0.0.1:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=19

note this loads fine on bit.no, but not local

![snap 2016-09-13 at 16 45 57](https://cloud.githubusercontent.com/assets/20817185/18478790/cf53125a-79d2-11e6-8fe9-f9758301200e.png)

**Comment by haschimoto** [comment]
seems to happen also on Chrome, it happens when clicking on videos in the sidebar

**Comment by haschimoto** [comment]
http://127.0.0.1:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=16

![snap 2016-09-17 at 10 38 05](https://cloud.githubusercontent.com/assets/20817185/18607094/fae08ea0-7cc2-11e6-8682-78c2c01869e6.png)

**Comment by dnelband** [comment]
implemented a solution, but lets keep this open for a couple of days
