### ISSUE TITLE
[central]: show video loading progress bar

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#5]
Example: http://mente.github.io/videojs-youtube-progress/

i think its called buffering:
https://github.com/mente/videojs-youtube-progress

http://blog.videojs.com/Video-js-v4-7-0-Built-mostly-by-NEW-contributors-Also-Google-chooses-Video-js/#Multiple-buffered-regions

**Comment by dnelband** [comment]
done

**Comment by haschimoto** [comment]
This is already much better :)

Now the question is:
Normally the "loading bar" is integrated in the videoplayers "timebar" (as in the example above), and while the first chunks load into buffer, the user can already start playing the video.

Can we do this with the videojs?

**Comment by dnelband** [comment]
not gonna work with the .json thing though. we can buffer an mp4 video but im not sure its possible to buffer dataURL

**Comment by haschimoto** [comment]
Does the videoplayer actually play a .json file or .mp4?

**Comment by dnelband** [comment]
Plays the .json by default, but the mp4 versions are there its possible
also to load them. Ill try, worst case we wont have buffering on ff for now

Am 11.08.2016 16:56 schrieb "haschimoto" notifications@github.com:

**Comment by dnelband** [comment]
chrome displays buffer, in ff it's a front-end solution. done
