### ISSUE TITLE
[upload video]: video upload doesnt seem to work ( /121zJWqw1n6wGhQhsyHQMqDtJACLTMh7kH )

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#52]
i uploaded a video to a newly cloned channel and it simply shows "Upload Video" button again after a while. That is confusing. It should go back to "Overview" when video uploading is done.

**Comment by haschimoto** [comment]
When going back manually to overview, the video list is completely empty, but under "optional files" the exact size of uploaded video is shown.
Also noticed it claims to have 3 videos on there...

**Comment by dnelband** [comment]
fixed, please test. do we want to keep the upload function? if so i will make it look like the edit view

**Comment by haschimoto** [comment]
i cant completely remove the newly cloned channel from ZN, you now it lives on forever even if emptied?

**Comment by haschimoto** [comment]
well, i now copied the files manually to my channel.
