### ISSUE TITLE
[register]: "Add Channel" shows green confirmation "Channel added", but then the channel doesnt seem to appear in the list

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#54]
channel i tried to add LOCAL:
/121zJWqw1n6wGhQhsyHQMqDtJACLTMh7kH
Maybe on the new register site, it doesnt allow any user to add channels to get signed and published?

**Comment by dnelband** [comment]
fixed, please test

**Comment by haschimoto** [comment]
it still does show the channel info, but when clicking the button, it does no longer show the green confirmation (site added), it simply reloads the register main page without the channel added.

**Comment by haschimoto** [comment]
im testing here btw: 17GijTrkMfxhTKWFnM2atrGVaZcp5zNBEW

**Comment by dnelband** [comment]
test on bit.no, added this channel - "Ninja Turtles", please test again
