### ISSUE TITLE
[register]: cant load sidebar (getting an error, even if delete site completely and reload new)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#56]
![snap 2016-09-18 at 23 22 25](https://cloud.githubusercontent.com/assets/20817185/18619205/ded6071e-7df6-11e6-8f3e-1516659d6f36.png)

**Comment by haschimoto** [comment]
maybe that is the reason why any channel added LOCAL is not stored?

**Comment by haschimoto** [comment]
well, seems I also cannot load sidebar on BITNO, even if picked a user:
![snap 2016-09-18 at 23 26 41](https://cloud.githubusercontent.com/assets/20817185/18619220/70756138-7df7-11e6-878e-218cfe8dc9de.png)

**Comment by dnelband** [comment]
no its not connected to the other bug. i need to wait for an answer on this one from tamas / github, its not clear to me why it does that.

**Comment by haschimoto** [comment]
imo this might be related... since i cant load the sidebar, i cant change my id for this site, maybe thats why i cant also sign and publish it or my credentials is not accepted for publish and sign.

**Comment by dnelband** [comment]
yeah you were right both of these problems originated from an issue with the "data/users/content.json", it was not signed currectly. now its fixed, tested local + bit.no, please test
