### ISSUE TITLE
[register]: remove userids from all data.json under /data/user/..../data.json

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#57]
this is imo an unneceesary risk. 
why not someone simply add a valid channel without a useris?

**Comment by dnelband** [comment]
force of habit, removed.

**Comment by haschimoto** [comment]
lets remove manually then all userids from any of the /data/user/..../data.json

**Comment by dnelband** [comment]
its not possible, we can only remove data from /data/user/..../data.json's which belong to our users. when i tried to delete things manually we started having that problem with the <> hash (and there after missing files etc') it creats problems and also doesnt publish these changes  to other users so it wont work

**Comment by dnelband** [comment]
zeronet needs the users private key in order to make changes to his files (data/users/...../)
