### ISSUE TITLE
[register] all user folders are missing on BITNO

### ISSUE THREAD

**Issue by dnelband** [zer0net/_ppload-videorama-tickets#59]
hi, something suddenly went wrong, i see no channels on bit.no, it seems as though all the user directories are missing, i didnt touch it so could be either someone deleted something or just bit.no is problematic for the time being. local i see everything normal

**Comment by dnelband** [comment]
this off course means that central on bit.no shows no videos, because register doesnt have any data.json's

**Comment by haschimoto** [comment]
BITNO and LOCAL...

**Comment by haschimoto** [comment]
are you programming the register site yourself? Have you noticed it suddenly become from a normal site to a merger hub??
