### ISSUE TITLE
[general]: add mp3 since it is supported by videojs

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#6]
http://blog.videojs.com/Video-js-4-9-Now-can-join-the-party/

**Comment by haschimoto** [comment]
mp3 is here, but cant be played:
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/

**Comment by dnelband** [comment]
done, now plays mp3 @ zerovidz central + user

**Comment by haschimoto** [comment]
awesome
