### ISSUE TITLE
[user]: synchronize channel name and website name

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#9]
e.g. https://bit.no.com:43110/128cqaMfWwAh6F8FKcdqNiFBZBgLXshGkM/

Channel name: 80s Channel :)
Zite name: Bla Video2
1. [ ] If you first clone a site, initialize the channel name with the cloned website name
2. [x] If you edit the name of the channel, update website name too

**Comment by dnelband** [comment]
done, the first task is currently not supported by the API
